// Code generated by ent, DO NOT EDIT.

package modelvendor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldName, v))
}

// ProviderKey applies equality check predicate on the "provider_key" field. It's identical to ProviderKeyEQ.
func ProviderKey(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldProviderKey, v))
}

// IconKey applies equality check predicate on the "icon_key" field. It's identical to IconKeyEQ.
func IconKey(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldIconKey, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldDescription, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContainsFold(FieldName, v))
}

// ProviderKeyEQ applies the EQ predicate on the "provider_key" field.
func ProviderKeyEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldProviderKey, v))
}

// ProviderKeyNEQ applies the NEQ predicate on the "provider_key" field.
func ProviderKeyNEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldProviderKey, v))
}

// ProviderKeyIn applies the In predicate on the "provider_key" field.
func ProviderKeyIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldProviderKey, vs...))
}

// ProviderKeyNotIn applies the NotIn predicate on the "provider_key" field.
func ProviderKeyNotIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldProviderKey, vs...))
}

// ProviderKeyGT applies the GT predicate on the "provider_key" field.
func ProviderKeyGT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldProviderKey, v))
}

// ProviderKeyGTE applies the GTE predicate on the "provider_key" field.
func ProviderKeyGTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldProviderKey, v))
}

// ProviderKeyLT applies the LT predicate on the "provider_key" field.
func ProviderKeyLT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldProviderKey, v))
}

// ProviderKeyLTE applies the LTE predicate on the "provider_key" field.
func ProviderKeyLTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldProviderKey, v))
}

// ProviderKeyContains applies the Contains predicate on the "provider_key" field.
func ProviderKeyContains(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContains(FieldProviderKey, v))
}

// ProviderKeyHasPrefix applies the HasPrefix predicate on the "provider_key" field.
func ProviderKeyHasPrefix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasPrefix(FieldProviderKey, v))
}

// ProviderKeyHasSuffix applies the HasSuffix predicate on the "provider_key" field.
func ProviderKeyHasSuffix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasSuffix(FieldProviderKey, v))
}

// ProviderKeyEqualFold applies the EqualFold predicate on the "provider_key" field.
func ProviderKeyEqualFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEqualFold(FieldProviderKey, v))
}

// ProviderKeyContainsFold applies the ContainsFold predicate on the "provider_key" field.
func ProviderKeyContainsFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContainsFold(FieldProviderKey, v))
}

// IconKeyEQ applies the EQ predicate on the "icon_key" field.
func IconKeyEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldIconKey, v))
}

// IconKeyNEQ applies the NEQ predicate on the "icon_key" field.
func IconKeyNEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldIconKey, v))
}

// IconKeyIn applies the In predicate on the "icon_key" field.
func IconKeyIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldIconKey, vs...))
}

// IconKeyNotIn applies the NotIn predicate on the "icon_key" field.
func IconKeyNotIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldIconKey, vs...))
}

// IconKeyGT applies the GT predicate on the "icon_key" field.
func IconKeyGT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldIconKey, v))
}

// IconKeyGTE applies the GTE predicate on the "icon_key" field.
func IconKeyGTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldIconKey, v))
}

// IconKeyLT applies the LT predicate on the "icon_key" field.
func IconKeyLT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldIconKey, v))
}

// IconKeyLTE applies the LTE predicate on the "icon_key" field.
func IconKeyLTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldIconKey, v))
}

// IconKeyContains applies the Contains predicate on the "icon_key" field.
func IconKeyContains(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContains(FieldIconKey, v))
}

// IconKeyHasPrefix applies the HasPrefix predicate on the "icon_key" field.
func IconKeyHasPrefix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasPrefix(FieldIconKey, v))
}

// IconKeyHasSuffix applies the HasSuffix predicate on the "icon_key" field.
func IconKeyHasSuffix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasSuffix(FieldIconKey, v))
}

// IconKeyEqualFold applies the EqualFold predicate on the "icon_key" field.
func IconKeyEqualFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEqualFold(FieldIconKey, v))
}

// IconKeyContainsFold applies the ContainsFold predicate on the "icon_key" field.
func IconKeyContainsFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContainsFold(FieldIconKey, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldContainsFold(FieldDescription, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.ModelVendor {
	return predicate.ModelVendor(sql.FieldLTE(FieldSortOrder, v))
}

// HasModels applies the HasEdge predicate on the "models" edge.
func HasModels() predicate.ModelVendor {
	return predicate.ModelVendor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ModelsTable, ModelsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelsWith applies the HasEdge predicate on the "models" edge with a given conditions (other predicates).
func HasModelsWith(preds ...predicate.ModelCatalog) predicate.ModelVendor {
	return predicate.ModelVendor(func(s *sql.Selector) {
		step := newModelsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelVendor) predicate.ModelVendor {
	return predicate.ModelVendor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelVendor) predicate.ModelVendor {
	return predicate.ModelVendor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelVendor) predicate.ModelVendor {
	return predicate.ModelVendor(sql.NotPredicates(p))
}
