// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
)

// ModelCatalogCreate is the builder for creating a ModelCatalog entity.
type ModelCatalogCreate struct {
	config
	mutation *ModelCatalogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCatalogCreate) SetCreatedAt(v time.Time) *ModelCatalogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableCreatedAt(v *time.Time) *ModelCatalogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCatalogCreate) SetUpdatedAt(v time.Time) *ModelCatalogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableUpdatedAt(v *time.Time) *ModelCatalogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *ModelCatalogCreate) SetModelID(v string) *ModelCatalogCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetNormalizedModelID sets the "normalized_model_id" field.
func (_c *ModelCatalogCreate) SetNormalizedModelID(v string) *ModelCatalogCreate {
	_c.mutation.SetNormalizedModelID(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *ModelCatalogCreate) SetDisplayName(v string) *ModelCatalogCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableDisplayName(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *ModelCatalogCreate) SetPlatform(v string) *ModelCatalogCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillablePlatform(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ModelCatalogCreate) SetProvider(v string) *ModelCatalogCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableProvider(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetVendorID sets the "vendor_id" field.
func (_c *ModelCatalogCreate) SetVendorID(v int64) *ModelCatalogCreate {
	_c.mutation.SetVendorID(v)
	return _c
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableVendorID(v *int64) *ModelCatalogCreate {
	if v != nil {
		_c.SetVendorID(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *ModelCatalogCreate) SetMode(v string) *ModelCatalogCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableMode(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ModelCatalogCreate) SetDescription(v string) *ModelCatalogCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableDescription(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ModelCatalogCreate) SetTags(v []string) *ModelCatalogCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetCapabilities sets the "capabilities" field.
func (_c *ModelCatalogCreate) SetCapabilities(v map[string]interface{}) *ModelCatalogCreate {
	_c.mutation.SetCapabilities(v)
	return _c
}

// SetEndpoints sets the "endpoints" field.
func (_c *ModelCatalogCreate) SetEndpoints(v []string) *ModelCatalogCreate {
	_c.mutation.SetEndpoints(v)
	return _c
}

// SetPricing sets the "pricing" field.
func (_c *ModelCatalogCreate) SetPricing(v map[string]interface{}) *ModelCatalogCreate {
	_c.mutation.SetPricing(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ModelCatalogCreate) SetMetadata(v map[string]interface{}) *ModelCatalogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelCatalogCreate) SetStatus(v modelcatalog.Status) *ModelCatalogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableStatus(v *modelcatalog.Status) *ModelCatalogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVisibility sets the "visibility" field.
func (_c *ModelCatalogCreate) SetVisibility(v modelcatalog.Visibility) *ModelCatalogCreate {
	_c.mutation.SetVisibility(v)
	return _c
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableVisibility(v *modelcatalog.Visibility) *ModelCatalogCreate {
	if v != nil {
		_c.SetVisibility(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *ModelCatalogCreate) SetSource(v string) *ModelCatalogCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableSource(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetIconKey sets the "icon_key" field.
func (_c *ModelCatalogCreate) SetIconKey(v string) *ModelCatalogCreate {
	_c.mutation.SetIconKey(v)
	return _c
}

// SetNillableIconKey sets the "icon_key" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableIconKey(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetIconKey(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *ModelCatalogCreate) SetLastSyncedAt(v time.Time) *ModelCatalogCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableLastSyncedAt(v *time.Time) *ModelCatalogCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetVendor sets the "vendor" edge to the ModelVendor entity.
func (_c *ModelCatalogCreate) SetVendor(v *ModelVendor) *ModelCatalogCreate {
	return _c.SetVendorID(v.ID)
}

// Mutation returns the ModelCatalogMutation object of the builder.
func (_c *ModelCatalogCreate) Mutation() *ModelCatalogMutation {
	return _c.mutation
}

// Save creates the ModelCatalog in the database.
func (_c *ModelCatalogCreate) Save(ctx context.Context) (*ModelCatalog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCatalogCreate) SaveX(ctx context.Context) *ModelCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCatalogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcatalog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcatalog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := modelcatalog.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := modelcatalog.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := modelcatalog.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := modelcatalog.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := modelcatalog.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := modelcatalog.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		v := modelcatalog.DefaultCapabilities
		_c.mutation.SetCapabilities(v)
	}
	if _, ok := _c.mutation.Endpoints(); !ok {
		v := modelcatalog.DefaultEndpoints
		_c.mutation.SetEndpoints(v)
	}
	if _, ok := _c.mutation.Pricing(); !ok {
		v := modelcatalog.DefaultPricing
		_c.mutation.SetPricing(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := modelcatalog.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := modelcatalog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		v := modelcatalog.DefaultVisibility
		_c.mutation.SetVisibility(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := modelcatalog.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.IconKey(); !ok {
		v := modelcatalog.DefaultIconKey
		_c.mutation.SetIconKey(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCatalogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCatalog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCatalog.updated_at"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "ModelCatalog.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := modelcatalog.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NormalizedModelID(); !ok {
		return &ValidationError{Name: "normalized_model_id", err: errors.New(`ent: missing required field "ModelCatalog.normalized_model_id"`)}
	}
	if v, ok := _c.mutation.NormalizedModelID(); ok {
		if err := modelcatalog.NormalizedModelIDValidator(v); err != nil {
			return &ValidationError{Name: "normalized_model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.normalized_model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "ModelCatalog.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := modelcatalog.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "ModelCatalog.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := modelcatalog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "ModelCatalog.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := modelcatalog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "ModelCatalog.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := modelcatalog.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ModelCatalog.description"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "ModelCatalog.tags"`)}
	}
	if _, ok := _c.mutation.Capabilities(); !ok {
		return &ValidationError{Name: "capabilities", err: errors.New(`ent: missing required field "ModelCatalog.capabilities"`)}
	}
	if _, ok := _c.mutation.Endpoints(); !ok {
		return &ValidationError{Name: "endpoints", err: errors.New(`ent: missing required field "ModelCatalog.endpoints"`)}
	}
	if _, ok := _c.mutation.Pricing(); !ok {
		return &ValidationError{Name: "pricing", err: errors.New(`ent: missing required field "ModelCatalog.pricing"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "ModelCatalog.metadata"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelCatalog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := modelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Visibility(); !ok {
		return &ValidationError{Name: "visibility", err: errors.New(`ent: missing required field "ModelCatalog.visibility"`)}
	}
	if v, ok := _c.mutation.Visibility(); ok {
		if err := modelcatalog.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.visibility": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ModelCatalog.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := modelcatalog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IconKey(); !ok {
		return &ValidationError{Name: "icon_key", err: errors.New(`ent: missing required field "ModelCatalog.icon_key"`)}
	}
	if v, ok := _c.mutation.IconKey(); ok {
		if err := modelcatalog.IconKeyValidator(v); err != nil {
			return &ValidationError{Name: "icon_key", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.icon_key": %w`, err)}
		}
	}
	return nil
}

func (_c *ModelCatalogCreate) sqlSave(ctx context.Context) (*ModelCatalog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCatalogCreate) createSpec() (*ModelCatalog, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCatalog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcatalog.Table, sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcatalog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(modelcatalog.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.NormalizedModelID(); ok {
		_spec.SetField(modelcatalog.FieldNormalizedModelID, field.TypeString, value)
		_node.NormalizedModelID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(modelcatalog.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(modelcatalog.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(modelcatalog.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(modelcatalog.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(modelcatalog.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(modelcatalog.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Capabilities(); ok {
		_spec.SetField(modelcatalog.FieldCapabilities, field.TypeJSON, value)
		_node.Capabilities = value
	}
	if value, ok := _c.mutation.Endpoints(); ok {
		_spec.SetField(modelcatalog.FieldEndpoints, field.TypeJSON, value)
		_node.Endpoints = value
	}
	if value, ok := _c.mutation.Pricing(); ok {
		_spec.SetField(modelcatalog.FieldPricing, field.TypeJSON, value)
		_node.Pricing = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(modelcatalog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelcatalog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Visibility(); ok {
		_spec.SetField(modelcatalog.FieldVisibility, field.TypeEnum, value)
		_node.Visibility = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(modelcatalog.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.IconKey(); ok {
		_spec.SetField(modelcatalog.FieldIconKey, field.TypeString, value)
		_node.IconKey = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(modelcatalog.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	if nodes := _c.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalog.VendorTable,
			Columns: []string{modelcatalog.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VendorID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogCreate) OnConflict(opts ...sql.ConflictOption) *ModelCatalogUpsertOne {
	_c.conflict = opts
	return &ModelCatalogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogCreate) OnConflictColumns(columns ...string) *ModelCatalogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogUpsertOne{
		create: _c,
	}
}

type (
	// ModelCatalogUpsertOne is the builder for "upsert"-ing
	//  one ModelCatalog node.
	ModelCatalogUpsertOne struct {
		create *ModelCatalogCreate
	}

	// ModelCatalogUpsert is the "OnConflict" setter.
	ModelCatalogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogUpsert) SetUpdatedAt(v time.Time) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateUpdatedAt() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldUpdatedAt)
	return u
}

// SetModelID sets the "model_id" field.
func (u *ModelCatalogUpsert) SetModelID(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateModelID() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldModelID)
	return u
}

// SetNormalizedModelID sets the "normalized_model_id" field.
func (u *ModelCatalogUpsert) SetNormalizedModelID(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldNormalizedModelID, v)
	return u
}

// UpdateNormalizedModelID sets the "normalized_model_id" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateNormalizedModelID() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldNormalizedModelID)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *ModelCatalogUpsert) SetDisplayName(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateDisplayName() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldDisplayName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *ModelCatalogUpsert) SetPlatform(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdatePlatform() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldPlatform)
	return u
}

// SetProvider sets the "provider" field.
func (u *ModelCatalogUpsert) SetProvider(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateProvider() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldProvider)
	return u
}

// SetVendorID sets the "vendor_id" field.
func (u *ModelCatalogUpsert) SetVendorID(v int64) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldVendorID, v)
	return u
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateVendorID() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldVendorID)
	return u
}

// ClearVendorID clears the value of the "vendor_id" field.
func (u *ModelCatalogUpsert) ClearVendorID() *ModelCatalogUpsert {
	u.SetNull(modelcatalog.FieldVendorID)
	return u
}

// SetMode sets the "mode" field.
func (u *ModelCatalogUpsert) SetMode(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateMode() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldMode)
	return u
}

// SetDescription sets the "description" field.
func (u *ModelCatalogUpsert) SetDescription(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateDescription() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldDescription)
	return u
}

// SetTags sets the "tags" field.
func (u *ModelCatalogUpsert) SetTags(v []string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateTags() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldTags)
	return u
}

// SetCapabilities sets the "capabilities" field.
func (u *ModelCatalogUpsert) SetCapabilities(v map[string]interface{}) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldCapabilities, v)
	return u
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateCapabilities() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldCapabilities)
	return u
}

// SetEndpoints sets the "endpoints" field.
func (u *ModelCatalogUpsert) SetEndpoints(v []string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldEndpoints, v)
	return u
}

// UpdateEndpoints sets the "endpoints" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateEndpoints() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldEndpoints)
	return u
}

// SetPricing sets the "pricing" field.
func (u *ModelCatalogUpsert) SetPricing(v map[string]interface{}) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldPricing, v)
	return u
}

// UpdatePricing sets the "pricing" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdatePricing() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldPricing)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ModelCatalogUpsert) SetMetadata(v map[string]interface{}) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateMetadata() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldMetadata)
	return u
}

// SetStatus sets the "status" field.
func (u *ModelCatalogUpsert) SetStatus(v modelcatalog.Status) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateStatus() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldStatus)
	return u
}

// SetVisibility sets the "visibility" field.
func (u *ModelCatalogUpsert) SetVisibility(v modelcatalog.Visibility) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldVisibility, v)
	return u
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateVisibility() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldVisibility)
	return u
}

// SetSource sets the "source" field.
func (u *ModelCatalogUpsert) SetSource(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateSource() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldSource)
	return u
}

// SetIconKey sets the "icon_key" field.
func (u *ModelCatalogUpsert) SetIconKey(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldIconKey, v)
	return u
}

// UpdateIconKey sets the "icon_key" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateIconKey() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldIconKey)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ModelCatalogUpsert) SetLastSyncedAt(v time.Time) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateLastSyncedAt() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldLastSyncedAt)
	return u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *ModelCatalogUpsert) ClearLastSyncedAt() *ModelCatalogUpsert {
	u.SetNull(modelcatalog.FieldLastSyncedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogUpsertOne) UpdateNewValues() *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelcatalog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelCatalogUpsertOne) Ignore() *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogUpsertOne) DoNothing() *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogCreate.OnConflict
// documentation for more info.
func (u *ModelCatalogUpsertOne) Update(set func(*ModelCatalogUpsert)) *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogUpsertOne) SetUpdatedAt(v time.Time) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateUpdatedAt() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModelID sets the "model_id" field.
func (u *ModelCatalogUpsertOne) SetModelID(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateModelID() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateModelID()
	})
}

// SetNormalizedModelID sets the "normalized_model_id" field.
func (u *ModelCatalogUpsertOne) SetNormalizedModelID(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetNormalizedModelID(v)
	})
}

// UpdateNormalizedModelID sets the "normalized_model_id" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateNormalizedModelID() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateNormalizedModelID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ModelCatalogUpsertOne) SetDisplayName(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateDisplayName() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateDisplayName()
	})
}

// SetPlatform sets the "platform" field.
func (u *ModelCatalogUpsertOne) SetPlatform(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdatePlatform() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdatePlatform()
	})
}

// SetProvider sets the "provider" field.
func (u *ModelCatalogUpsertOne) SetProvider(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateProvider() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateProvider()
	})
}

// SetVendorID sets the "vendor_id" field.
func (u *ModelCatalogUpsertOne) SetVendorID(v int64) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetVendorID(v)
	})
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateVendorID() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateVendorID()
	})
}

// ClearVendorID clears the value of the "vendor_id" field.
func (u *ModelCatalogUpsertOne) ClearVendorID() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearVendorID()
	})
}

// SetMode sets the "mode" field.
func (u *ModelCatalogUpsertOne) SetMode(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateMode() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateMode()
	})
}

// SetDescription sets the "description" field.
func (u *ModelCatalogUpsertOne) SetDescription(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateDescription() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateDescription()
	})
}

// SetTags sets the "tags" field.
func (u *ModelCatalogUpsertOne) SetTags(v []string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateTags() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateTags()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *ModelCatalogUpsertOne) SetCapabilities(v map[string]interface{}) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateCapabilities() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateCapabilities()
	})
}

// SetEndpoints sets the "endpoints" field.
func (u *ModelCatalogUpsertOne) SetEndpoints(v []string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetEndpoints(v)
	})
}

// UpdateEndpoints sets the "endpoints" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateEndpoints() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateEndpoints()
	})
}

// SetPricing sets the "pricing" field.
func (u *ModelCatalogUpsertOne) SetPricing(v map[string]interface{}) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetPricing(v)
	})
}

// UpdatePricing sets the "pricing" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdatePricing() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdatePricing()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ModelCatalogUpsertOne) SetMetadata(v map[string]interface{}) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateMetadata() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateMetadata()
	})
}

// SetStatus sets the "status" field.
func (u *ModelCatalogUpsertOne) SetStatus(v modelcatalog.Status) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateStatus() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateStatus()
	})
}

// SetVisibility sets the "visibility" field.
func (u *ModelCatalogUpsertOne) SetVisibility(v modelcatalog.Visibility) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateVisibility() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateVisibility()
	})
}

// SetSource sets the "source" field.
func (u *ModelCatalogUpsertOne) SetSource(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateSource() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateSource()
	})
}

// SetIconKey sets the "icon_key" field.
func (u *ModelCatalogUpsertOne) SetIconKey(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetIconKey(v)
	})
}

// UpdateIconKey sets the "icon_key" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateIconKey() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateIconKey()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ModelCatalogUpsertOne) SetLastSyncedAt(v time.Time) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateLastSyncedAt() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *ModelCatalogUpsertOne) ClearLastSyncedAt() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearLastSyncedAt()
	})
}

// Exec executes the query.
func (u *ModelCatalogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelCatalogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelCatalogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelCatalogCreateBulk is the builder for creating many ModelCatalog entities in bulk.
type ModelCatalogCreateBulk struct {
	config
	err      error
	builders []*ModelCatalogCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelCatalog entities in the database.
func (_c *ModelCatalogCreateBulk) Save(ctx context.Context) ([]*ModelCatalog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCatalog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCatalogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCatalogCreateBulk) SaveX(ctx context.Context) []*ModelCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelCatalogUpsertBulk {
	_c.conflict = opts
	return &ModelCatalogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogCreateBulk) OnConflictColumns(columns ...string) *ModelCatalogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogUpsertBulk{
		create: _c,
	}
}

// ModelCatalogUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelCatalog nodes.
type ModelCatalogUpsertBulk struct {
	create *ModelCatalogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelCatalogUpsertBulk) UpdateNewValues() *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelcatalog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelCatalogUpsertBulk) Ignore() *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogUpsertBulk) DoNothing() *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogCreateBulk.OnConflict
// documentation for more info.
func (u *ModelCatalogUpsertBulk) Update(set func(*ModelCatalogUpsert)) *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogUpsertBulk) SetUpdatedAt(v time.Time) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateUpdatedAt() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetModelID sets the "model_id" field.
func (u *ModelCatalogUpsertBulk) SetModelID(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateModelID() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateModelID()
	})
}

// SetNormalizedModelID sets the "normalized_model_id" field.
func (u *ModelCatalogUpsertBulk) SetNormalizedModelID(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetNormalizedModelID(v)
	})
}

// UpdateNormalizedModelID sets the "normalized_model_id" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateNormalizedModelID() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateNormalizedModelID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *ModelCatalogUpsertBulk) SetDisplayName(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateDisplayName() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateDisplayName()
	})
}

// SetPlatform sets the "platform" field.
func (u *ModelCatalogUpsertBulk) SetPlatform(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdatePlatform() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdatePlatform()
	})
}

// SetProvider sets the "provider" field.
func (u *ModelCatalogUpsertBulk) SetProvider(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateProvider() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateProvider()
	})
}

// SetVendorID sets the "vendor_id" field.
func (u *ModelCatalogUpsertBulk) SetVendorID(v int64) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetVendorID(v)
	})
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateVendorID() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateVendorID()
	})
}

// ClearVendorID clears the value of the "vendor_id" field.
func (u *ModelCatalogUpsertBulk) ClearVendorID() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearVendorID()
	})
}

// SetMode sets the "mode" field.
func (u *ModelCatalogUpsertBulk) SetMode(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateMode() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateMode()
	})
}

// SetDescription sets the "description" field.
func (u *ModelCatalogUpsertBulk) SetDescription(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateDescription() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateDescription()
	})
}

// SetTags sets the "tags" field.
func (u *ModelCatalogUpsertBulk) SetTags(v []string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateTags() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateTags()
	})
}

// SetCapabilities sets the "capabilities" field.
func (u *ModelCatalogUpsertBulk) SetCapabilities(v map[string]interface{}) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetCapabilities(v)
	})
}

// UpdateCapabilities sets the "capabilities" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateCapabilities() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateCapabilities()
	})
}

// SetEndpoints sets the "endpoints" field.
func (u *ModelCatalogUpsertBulk) SetEndpoints(v []string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetEndpoints(v)
	})
}

// UpdateEndpoints sets the "endpoints" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateEndpoints() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateEndpoints()
	})
}

// SetPricing sets the "pricing" field.
func (u *ModelCatalogUpsertBulk) SetPricing(v map[string]interface{}) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetPricing(v)
	})
}

// UpdatePricing sets the "pricing" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdatePricing() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdatePricing()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ModelCatalogUpsertBulk) SetMetadata(v map[string]interface{}) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateMetadata() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateMetadata()
	})
}

// SetStatus sets the "status" field.
func (u *ModelCatalogUpsertBulk) SetStatus(v modelcatalog.Status) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateStatus() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateStatus()
	})
}

// SetVisibility sets the "visibility" field.
func (u *ModelCatalogUpsertBulk) SetVisibility(v modelcatalog.Visibility) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetVisibility(v)
	})
}

// UpdateVisibility sets the "visibility" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateVisibility() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateVisibility()
	})
}

// SetSource sets the "source" field.
func (u *ModelCatalogUpsertBulk) SetSource(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateSource() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateSource()
	})
}

// SetIconKey sets the "icon_key" field.
func (u *ModelCatalogUpsertBulk) SetIconKey(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetIconKey(v)
	})
}

// UpdateIconKey sets the "icon_key" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateIconKey() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateIconKey()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *ModelCatalogUpsertBulk) SetLastSyncedAt(v time.Time) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateLastSyncedAt() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (u *ModelCatalogUpsertBulk) ClearLastSyncedAt() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearLastSyncedAt()
	})
}

// Exec executes the query.
func (u *ModelCatalogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCatalogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
