// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
)

// ModelVendorCreate is the builder for creating a ModelVendor entity.
type ModelVendorCreate struct {
	config
	mutation *ModelVendorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelVendorCreate) SetCreatedAt(v time.Time) *ModelVendorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelVendorCreate) SetNillableCreatedAt(v *time.Time) *ModelVendorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelVendorCreate) SetUpdatedAt(v time.Time) *ModelVendorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelVendorCreate) SetNillableUpdatedAt(v *time.Time) *ModelVendorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ModelVendorCreate) SetName(v string) *ModelVendorCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProviderKey sets the "provider_key" field.
func (_c *ModelVendorCreate) SetProviderKey(v string) *ModelVendorCreate {
	_c.mutation.SetProviderKey(v)
	return _c
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_c *ModelVendorCreate) SetNillableProviderKey(v *string) *ModelVendorCreate {
	if v != nil {
		_c.SetProviderKey(*v)
	}
	return _c
}

// SetIconKey sets the "icon_key" field.
func (_c *ModelVendorCreate) SetIconKey(v string) *ModelVendorCreate {
	_c.mutation.SetIconKey(v)
	return _c
}

// SetNillableIconKey sets the "icon_key" field if the given value is not nil.
func (_c *ModelVendorCreate) SetNillableIconKey(v *string) *ModelVendorCreate {
	if v != nil {
		_c.SetIconKey(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *ModelVendorCreate) SetDescription(v string) *ModelVendorCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ModelVendorCreate) SetNillableDescription(v *string) *ModelVendorCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ModelVendorCreate) SetSortOrder(v int) *ModelVendorCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ModelVendorCreate) SetNillableSortOrder(v *int) *ModelVendorCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddModelIDs adds the "models" edge to the ModelCatalog entity by IDs.
func (_c *ModelVendorCreate) AddModelIDs(ids ...int64) *ModelVendorCreate {
	_c.mutation.AddModelIDs(ids...)
	return _c
}

// AddModels adds the "models" edges to the ModelCatalog entity.
func (_c *ModelVendorCreate) AddModels(v ...*ModelCatalog) *ModelVendorCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddModelIDs(ids...)
}

// Mutation returns the ModelVendorMutation object of the builder.
func (_c *ModelVendorCreate) Mutation() *ModelVendorMutation {
	return _c.mutation
}

// Save creates the ModelVendor in the database.
func (_c *ModelVendorCreate) Save(ctx context.Context) (*ModelVendor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelVendorCreate) SaveX(ctx context.Context) *ModelVendor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelVendorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelVendorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelVendorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelvendor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelvendor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ProviderKey(); !ok {
		v := modelvendor.DefaultProviderKey
		_c.mutation.SetProviderKey(v)
	}
	if _, ok := _c.mutation.IconKey(); !ok {
		v := modelvendor.DefaultIconKey
		_c.mutation.SetIconKey(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := modelvendor.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := modelvendor.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelVendorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelVendor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelVendor.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ModelVendor.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := modelvendor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderKey(); !ok {
		return &ValidationError{Name: "provider_key", err: errors.New(`ent: missing required field "ModelVendor.provider_key"`)}
	}
	if v, ok := _c.mutation.ProviderKey(); ok {
		if err := modelvendor.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.provider_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IconKey(); !ok {
		return &ValidationError{Name: "icon_key", err: errors.New(`ent: missing required field "ModelVendor.icon_key"`)}
	}
	if v, ok := _c.mutation.IconKey(); ok {
		if err := modelvendor.IconKeyValidator(v); err != nil {
			return &ValidationError{Name: "icon_key", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.icon_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "ModelVendor.description"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ModelVendor.sort_order"`)}
	}
	return nil
}

func (_c *ModelVendorCreate) sqlSave(ctx context.Context) (*ModelVendor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelVendorCreate) createSpec() (*ModelVendor, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelVendor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelvendor.Table, sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelvendor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelvendor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(modelvendor.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ProviderKey(); ok {
		_spec.SetField(modelvendor.FieldProviderKey, field.TypeString, value)
		_node.ProviderKey = value
	}
	if value, ok := _c.mutation.IconKey(); ok {
		_spec.SetField(modelvendor.FieldIconKey, field.TypeString, value)
		_node.IconKey = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(modelvendor.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(modelvendor.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelVendor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelVendorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelVendorCreate) OnConflict(opts ...sql.ConflictOption) *ModelVendorUpsertOne {
	_c.conflict = opts
	return &ModelVendorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelVendor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelVendorCreate) OnConflictColumns(columns ...string) *ModelVendorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelVendorUpsertOne{
		create: _c,
	}
}

type (
	// ModelVendorUpsertOne is the builder for "upsert"-ing
	//  one ModelVendor node.
	ModelVendorUpsertOne struct {
		create *ModelVendorCreate
	}

	// ModelVendorUpsert is the "OnConflict" setter.
	ModelVendorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelVendorUpsert) SetUpdatedAt(v time.Time) *ModelVendorUpsert {
	u.Set(modelvendor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelVendorUpsert) UpdateUpdatedAt() *ModelVendorUpsert {
	u.SetExcluded(modelvendor.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *ModelVendorUpsert) SetName(v string) *ModelVendorUpsert {
	u.Set(modelvendor.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelVendorUpsert) UpdateName() *ModelVendorUpsert {
	u.SetExcluded(modelvendor.FieldName)
	return u
}

// SetProviderKey sets the "provider_key" field.
func (u *ModelVendorUpsert) SetProviderKey(v string) *ModelVendorUpsert {
	u.Set(modelvendor.FieldProviderKey, v)
	return u
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *ModelVendorUpsert) UpdateProviderKey() *ModelVendorUpsert {
	u.SetExcluded(modelvendor.FieldProviderKey)
	return u
}

// SetIconKey sets the "icon_key" field.
func (u *ModelVendorUpsert) SetIconKey(v string) *ModelVendorUpsert {
	u.Set(modelvendor.FieldIconKey, v)
	return u
}

// UpdateIconKey sets the "icon_key" field to the value that was provided on create.
func (u *ModelVendorUpsert) UpdateIconKey() *ModelVendorUpsert {
	u.SetExcluded(modelvendor.FieldIconKey)
	return u
}

// SetDescription sets the "description" field.
func (u *ModelVendorUpsert) SetDescription(v string) *ModelVendorUpsert {
	u.Set(modelvendor.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ModelVendorUpsert) UpdateDescription() *ModelVendorUpsert {
	u.SetExcluded(modelvendor.FieldDescription)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ModelVendorUpsert) SetSortOrder(v int) *ModelVendorUpsert {
	u.Set(modelvendor.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ModelVendorUpsert) UpdateSortOrder() *ModelVendorUpsert {
	u.SetExcluded(modelvendor.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ModelVendorUpsert) AddSortOrder(v int) *ModelVendorUpsert {
	u.Add(modelvendor.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ModelVendor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelVendorUpsertOne) UpdateNewValues() *ModelVendorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelvendor.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelVendor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelVendorUpsertOne) Ignore() *ModelVendorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelVendorUpsertOne) DoNothing() *ModelVendorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelVendorCreate.OnConflict
// documentation for more info.
func (u *ModelVendorUpsertOne) Update(set func(*ModelVendorUpsert)) *ModelVendorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelVendorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelVendorUpsertOne) SetUpdatedAt(v time.Time) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelVendorUpsertOne) UpdateUpdatedAt() *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ModelVendorUpsertOne) SetName(v string) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelVendorUpsertOne) UpdateName() *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateName()
	})
}

// SetProviderKey sets the "provider_key" field.
func (u *ModelVendorUpsertOne) SetProviderKey(v string) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *ModelVendorUpsertOne) UpdateProviderKey() *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateProviderKey()
	})
}

// SetIconKey sets the "icon_key" field.
func (u *ModelVendorUpsertOne) SetIconKey(v string) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetIconKey(v)
	})
}

// UpdateIconKey sets the "icon_key" field to the value that was provided on create.
func (u *ModelVendorUpsertOne) UpdateIconKey() *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateIconKey()
	})
}

// SetDescription sets the "description" field.
func (u *ModelVendorUpsertOne) SetDescription(v string) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ModelVendorUpsertOne) UpdateDescription() *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateDescription()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ModelVendorUpsertOne) SetSortOrder(v int) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ModelVendorUpsertOne) AddSortOrder(v int) *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ModelVendorUpsertOne) UpdateSortOrder() *ModelVendorUpsertOne {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *ModelVendorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelVendorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelVendorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelVendorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelVendorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelVendorCreateBulk is the builder for creating many ModelVendor entities in bulk.
type ModelVendorCreateBulk struct {
	config
	err      error
	builders []*ModelVendorCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelVendor entities in the database.
func (_c *ModelVendorCreateBulk) Save(ctx context.Context) ([]*ModelVendor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelVendor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelVendorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelVendorCreateBulk) SaveX(ctx context.Context) []*ModelVendor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelVendorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelVendorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelVendor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelVendorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelVendorCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelVendorUpsertBulk {
	_c.conflict = opts
	return &ModelVendorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelVendor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelVendorCreateBulk) OnConflictColumns(columns ...string) *ModelVendorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelVendorUpsertBulk{
		create: _c,
	}
}

// ModelVendorUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelVendor nodes.
type ModelVendorUpsertBulk struct {
	create *ModelVendorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelVendor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ModelVendorUpsertBulk) UpdateNewValues() *ModelVendorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelvendor.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelVendor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelVendorUpsertBulk) Ignore() *ModelVendorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelVendorUpsertBulk) DoNothing() *ModelVendorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelVendorCreateBulk.OnConflict
// documentation for more info.
func (u *ModelVendorUpsertBulk) Update(set func(*ModelVendorUpsert)) *ModelVendorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelVendorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelVendorUpsertBulk) SetUpdatedAt(v time.Time) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelVendorUpsertBulk) UpdateUpdatedAt() *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *ModelVendorUpsertBulk) SetName(v string) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ModelVendorUpsertBulk) UpdateName() *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateName()
	})
}

// SetProviderKey sets the "provider_key" field.
func (u *ModelVendorUpsertBulk) SetProviderKey(v string) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetProviderKey(v)
	})
}

// UpdateProviderKey sets the "provider_key" field to the value that was provided on create.
func (u *ModelVendorUpsertBulk) UpdateProviderKey() *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateProviderKey()
	})
}

// SetIconKey sets the "icon_key" field.
func (u *ModelVendorUpsertBulk) SetIconKey(v string) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetIconKey(v)
	})
}

// UpdateIconKey sets the "icon_key" field to the value that was provided on create.
func (u *ModelVendorUpsertBulk) UpdateIconKey() *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateIconKey()
	})
}

// SetDescription sets the "description" field.
func (u *ModelVendorUpsertBulk) SetDescription(v string) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ModelVendorUpsertBulk) UpdateDescription() *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateDescription()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ModelVendorUpsertBulk) SetSortOrder(v int) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ModelVendorUpsertBulk) AddSortOrder(v int) *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ModelVendorUpsertBulk) UpdateSortOrder() *ModelVendorUpsertBulk {
	return u.Update(func(s *ModelVendorUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *ModelVendorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelVendorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelVendorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelVendorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
