// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
)

// ModelCatalog is the model entity for the ModelCatalog schema.
type ModelCatalog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// NormalizedModelID holds the value of the "normalized_model_id" field.
	NormalizedModelID string `json:"normalized_model_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// VendorID holds the value of the "vendor_id" field.
	VendorID *int64 `json:"vendor_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// Capabilities holds the value of the "capabilities" field.
	Capabilities map[string]interface{} `json:"capabilities,omitempty"`
	// Endpoints holds the value of the "endpoints" field.
	Endpoints []string `json:"endpoints,omitempty"`
	// Pricing holds the value of the "pricing" field.
	Pricing map[string]interface{} `json:"pricing,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Status holds the value of the "status" field.
	Status modelcatalog.Status `json:"status,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility modelcatalog.Visibility `json:"visibility,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// IconKey holds the value of the "icon_key" field.
	IconKey string `json:"icon_key,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelCatalogQuery when eager-loading is set.
	Edges        ModelCatalogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelCatalogEdges holds the relations/edges for other nodes in the graph.
type ModelCatalogEdges struct {
	// Vendor holds the value of the vendor edge.
	Vendor *ModelVendor `json:"vendor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VendorOrErr returns the Vendor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelCatalogEdges) VendorOrErr() (*ModelVendor, error) {
	if e.Vendor != nil {
		return e.Vendor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: modelvendor.Label}
	}
	return nil, &NotLoadedError{edge: "vendor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelCatalog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelcatalog.FieldTags, modelcatalog.FieldCapabilities, modelcatalog.FieldEndpoints, modelcatalog.FieldPricing, modelcatalog.FieldMetadata:
			values[i] = new([]byte)
		case modelcatalog.FieldID, modelcatalog.FieldVendorID:
			values[i] = new(sql.NullInt64)
		case modelcatalog.FieldModelID, modelcatalog.FieldNormalizedModelID, modelcatalog.FieldDisplayName, modelcatalog.FieldPlatform, modelcatalog.FieldProvider, modelcatalog.FieldMode, modelcatalog.FieldDescription, modelcatalog.FieldStatus, modelcatalog.FieldVisibility, modelcatalog.FieldSource, modelcatalog.FieldIconKey:
			values[i] = new(sql.NullString)
		case modelcatalog.FieldCreatedAt, modelcatalog.FieldUpdatedAt, modelcatalog.FieldLastSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelCatalog fields.
func (_m *ModelCatalog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelcatalog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelcatalog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelcatalog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelcatalog.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelcatalog.FieldNormalizedModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field normalized_model_id", values[i])
			} else if value.Valid {
				_m.NormalizedModelID = value.String
			}
		case modelcatalog.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case modelcatalog.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case modelcatalog.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case modelcatalog.FieldVendorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field vendor_id", values[i])
			} else if value.Valid {
				_m.VendorID = new(int64)
				*_m.VendorID = value.Int64
			}
		case modelcatalog.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case modelcatalog.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case modelcatalog.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case modelcatalog.FieldCapabilities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field capabilities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Capabilities); err != nil {
					return fmt.Errorf("unmarshal field capabilities: %w", err)
				}
			}
		case modelcatalog.FieldEndpoints:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field endpoints", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Endpoints); err != nil {
					return fmt.Errorf("unmarshal field endpoints: %w", err)
				}
			}
		case modelcatalog.FieldPricing:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pricing", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Pricing); err != nil {
					return fmt.Errorf("unmarshal field pricing: %w", err)
				}
			}
		case modelcatalog.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case modelcatalog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = modelcatalog.Status(value.String)
			}
		case modelcatalog.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				_m.Visibility = modelcatalog.Visibility(value.String)
			}
		case modelcatalog.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case modelcatalog.FieldIconKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_key", values[i])
			} else if value.Valid {
				_m.IconKey = value.String
			}
		case modelcatalog.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelCatalog.
// This includes values selected through modifiers, order, etc.
func (_m *ModelCatalog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVendor queries the "vendor" edge of the ModelCatalog entity.
func (_m *ModelCatalog) QueryVendor() *ModelVendorQuery {
	return NewModelCatalogClient(_m.config).QueryVendor(_m)
}

// Update returns a builder for updating this ModelCatalog.
// Note that you need to call ModelCatalog.Unwrap() before calling this method if this ModelCatalog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelCatalog) Update() *ModelCatalogUpdateOne {
	return NewModelCatalogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelCatalog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelCatalog) Unwrap() *ModelCatalog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelCatalog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelCatalog) String() string {
	var builder strings.Builder
	builder.WriteString("ModelCatalog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("normalized_model_id=")
	builder.WriteString(_m.NormalizedModelID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	if v := _m.VendorID; v != nil {
		builder.WriteString("vendor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	builder.WriteString("capabilities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Capabilities))
	builder.WriteString(", ")
	builder.WriteString("endpoints=")
	builder.WriteString(fmt.Sprintf("%v", _m.Endpoints))
	builder.WriteString(", ")
	builder.WriteString("pricing=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pricing))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", _m.Visibility))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("icon_key=")
	builder.WriteString(_m.IconKey)
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelCatalogs is a parsable slice of ModelCatalog.
type ModelCatalogs []*ModelCatalog
