// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelVendorDelete is the builder for deleting a ModelVendor entity.
type ModelVendorDelete struct {
	config
	hooks    []Hook
	mutation *ModelVendorMutation
}

// Where appends a list predicates to the ModelVendorDelete builder.
func (_d *ModelVendorDelete) Where(ps ...predicate.ModelVendor) *ModelVendorDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ModelVendorDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelVendorDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ModelVendorDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(modelvendor.Table, sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ModelVendorDeleteOne is the builder for deleting a single ModelVendor entity.
type ModelVendorDeleteOne struct {
	_d *ModelVendorDelete
}

// Where appends a list predicates to the ModelVendorDelete builder.
func (_d *ModelVendorDeleteOne) Where(ps ...predicate.ModelVendor) *ModelVendorDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ModelVendorDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{modelvendor.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ModelVendorDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
