// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
)

// ModelVendor is the model entity for the ModelVendor schema.
type ModelVendor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// IconKey holds the value of the "icon_key" field.
	IconKey string `json:"icon_key,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelVendorQuery when eager-loading is set.
	Edges        ModelVendorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelVendorEdges holds the relations/edges for other nodes in the graph.
type ModelVendorEdges struct {
	// Models holds the value of the models edge.
	Models []*ModelCatalog `json:"models,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModelsOrErr returns the Models value or an error if the edge
// was not loaded in eager-loading.
func (e ModelVendorEdges) ModelsOrErr() ([]*ModelCatalog, error) {
	if e.loadedTypes[0] {
		return e.Models, nil
	}
	return nil, &NotLoadedError{edge: "models"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelVendor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelvendor.FieldID, modelvendor.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case modelvendor.FieldName, modelvendor.FieldProviderKey, modelvendor.FieldIconKey, modelvendor.FieldDescription:
			values[i] = new(sql.NullString)
		case modelvendor.FieldCreatedAt, modelvendor.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelVendor fields.
func (_m *ModelVendor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelvendor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case modelvendor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelvendor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelvendor.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case modelvendor.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case modelvendor.FieldIconKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon_key", values[i])
			} else if value.Valid {
				_m.IconKey = value.String
			}
		case modelvendor.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case modelvendor.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelVendor.
// This includes values selected through modifiers, order, etc.
func (_m *ModelVendor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModels queries the "models" edge of the ModelVendor entity.
func (_m *ModelVendor) QueryModels() *ModelCatalogQuery {
	return NewModelVendorClient(_m.config).QueryModels(_m)
}

// Update returns a builder for updating this ModelVendor.
// Note that you need to call ModelVendor.Unwrap() before calling this method if this ModelVendor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelVendor) Update() *ModelVendorUpdateOne {
	return NewModelVendorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelVendor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelVendor) Unwrap() *ModelVendor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelVendor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelVendor) String() string {
	var builder strings.Builder
	builder.WriteString("ModelVendor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("icon_key=")
	builder.WriteString(_m.IconKey)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// ModelVendors is a parsable slice of ModelVendor.
type ModelVendors []*ModelVendor
