// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelVendorUpdate is the builder for updating ModelVendor entities.
type ModelVendorUpdate struct {
	config
	hooks    []Hook
	mutation *ModelVendorMutation
}

// Where appends a list predicates to the ModelVendorUpdate builder.
func (_u *ModelVendorUpdate) Where(ps ...predicate.ModelVendor) *ModelVendorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelVendorUpdate) SetUpdatedAt(v time.Time) *ModelVendorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ModelVendorUpdate) SetName(v string) *ModelVendorUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModelVendorUpdate) SetNillableName(v *string) *ModelVendorUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *ModelVendorUpdate) SetProviderKey(v string) *ModelVendorUpdate {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *ModelVendorUpdate) SetNillableProviderKey(v *string) *ModelVendorUpdate {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetIconKey sets the "icon_key" field.
func (_u *ModelVendorUpdate) SetIconKey(v string) *ModelVendorUpdate {
	_u.mutation.SetIconKey(v)
	return _u
}

// SetNillableIconKey sets the "icon_key" field if the given value is not nil.
func (_u *ModelVendorUpdate) SetNillableIconKey(v *string) *ModelVendorUpdate {
	if v != nil {
		_u.SetIconKey(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelVendorUpdate) SetDescription(v string) *ModelVendorUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelVendorUpdate) SetNillableDescription(v *string) *ModelVendorUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ModelVendorUpdate) SetSortOrder(v int) *ModelVendorUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ModelVendorUpdate) SetNillableSortOrder(v *int) *ModelVendorUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ModelVendorUpdate) AddSortOrder(v int) *ModelVendorUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelVendorUpdate) SetDeletedAt(v time.Time) *ModelVendorUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelVendorUpdate) SetNillableDeletedAt(v *time.Time) *ModelVendorUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ModelVendorUpdate) ClearDeletedAt() *ModelVendorUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddModelIDs adds the "models" edge to the ModelCatalog entity by IDs.
func (_u *ModelVendorUpdate) AddModelIDs(ids ...int64) *ModelVendorUpdate {
	_u.mutation.AddModelIDs(ids...)
	return _u
}

// AddModels adds the "models" edges to the ModelCatalog entity.
func (_u *ModelVendorUpdate) AddModels(v ...*ModelCatalog) *ModelVendorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelIDs(ids...)
}

// Mutation returns the ModelVendorMutation object of the builder.
func (_u *ModelVendorUpdate) Mutation() *ModelVendorMutation {
	return _u.mutation
}

// ClearModels clears all "models" edges to the ModelCatalog entity.
func (_u *ModelVendorUpdate) ClearModels() *ModelVendorUpdate {
	_u.mutation.ClearModels()
	return _u
}

// RemoveModelIDs removes the "models" edge to ModelCatalog entities by IDs.
func (_u *ModelVendorUpdate) RemoveModelIDs(ids ...int64) *ModelVendorUpdate {
	_u.mutation.RemoveModelIDs(ids...)
	return _u
}

// RemoveModels removes "models" edges to ModelCatalog entities.
func (_u *ModelVendorUpdate) RemoveModels(v ...*ModelCatalog) *ModelVendorUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelVendorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelVendorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelVendorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelVendorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelVendorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelvendor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelVendorUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := modelvendor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := modelvendor.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconKey(); ok {
		if err := modelvendor.IconKeyValidator(v); err != nil {
			return &ValidationError{Name: "icon_key", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.icon_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelVendorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelvendor.Table, modelvendor.Columns, sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelvendor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modelvendor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(modelvendor.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconKey(); ok {
		_spec.SetField(modelvendor.FieldIconKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelvendor.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(modelvendor.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(modelvendor.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelvendor.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(modelvendor.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelsIDs(); len(nodes) > 0 && !_u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelvendor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelVendorUpdateOne is the builder for updating a single ModelVendor entity.
type ModelVendorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelVendorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelVendorUpdateOne) SetUpdatedAt(v time.Time) *ModelVendorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ModelVendorUpdateOne) SetName(v string) *ModelVendorUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModelVendorUpdateOne) SetNillableName(v *string) *ModelVendorUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProviderKey sets the "provider_key" field.
func (_u *ModelVendorUpdateOne) SetProviderKey(v string) *ModelVendorUpdateOne {
	_u.mutation.SetProviderKey(v)
	return _u
}

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *ModelVendorUpdateOne) SetNillableProviderKey(v *string) *ModelVendorUpdateOne {
	if v != nil {
		_u.SetProviderKey(*v)
	}
	return _u
}

// SetIconKey sets the "icon_key" field.
func (_u *ModelVendorUpdateOne) SetIconKey(v string) *ModelVendorUpdateOne {
	_u.mutation.SetIconKey(v)
	return _u
}

// SetNillableIconKey sets the "icon_key" field if the given value is not nil.
func (_u *ModelVendorUpdateOne) SetNillableIconKey(v *string) *ModelVendorUpdateOne {
	if v != nil {
		_u.SetIconKey(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelVendorUpdateOne) SetDescription(v string) *ModelVendorUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelVendorUpdateOne) SetNillableDescription(v *string) *ModelVendorUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ModelVendorUpdateOne) SetSortOrder(v int) *ModelVendorUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ModelVendorUpdateOne) SetNillableSortOrder(v *int) *ModelVendorUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ModelVendorUpdateOne) AddSortOrder(v int) *ModelVendorUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModelVendorUpdateOne) SetDeletedAt(v time.Time) *ModelVendorUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModelVendorUpdateOne) SetNillableDeletedAt(v *time.Time) *ModelVendorUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ModelVendorUpdateOne) ClearDeletedAt() *ModelVendorUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddModelIDs adds the "models" edge to the ModelCatalog entity by IDs.
func (_u *ModelVendorUpdateOne) AddModelIDs(ids ...int64) *ModelVendorUpdateOne {
	_u.mutation.AddModelIDs(ids...)
	return _u
}

// AddModels adds the "models" edges to the ModelCatalog entity.
func (_u *ModelVendorUpdateOne) AddModels(v ...*ModelCatalog) *ModelVendorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelIDs(ids...)
}

// Mutation returns the ModelVendorMutation object of the builder.
func (_u *ModelVendorUpdateOne) Mutation() *ModelVendorMutation {
	return _u.mutation
}

// ClearModels clears all "models" edges to the ModelCatalog entity.
func (_u *ModelVendorUpdateOne) ClearModels() *ModelVendorUpdateOne {
	_u.mutation.ClearModels()
	return _u
}

// RemoveModelIDs removes the "models" edge to ModelCatalog entities by IDs.
func (_u *ModelVendorUpdateOne) RemoveModelIDs(ids ...int64) *ModelVendorUpdateOne {
	_u.mutation.RemoveModelIDs(ids...)
	return _u
}

// RemoveModels removes "models" edges to ModelCatalog entities.
func (_u *ModelVendorUpdateOne) RemoveModels(v ...*ModelCatalog) *ModelVendorUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelIDs(ids...)
}

// Where appends a list predicates to the ModelVendorUpdate builder.
func (_u *ModelVendorUpdateOne) Where(ps ...predicate.ModelVendor) *ModelVendorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelVendorUpdateOne) Select(field string, fields ...string) *ModelVendorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelVendor entity.
func (_u *ModelVendorUpdateOne) Save(ctx context.Context) (*ModelVendor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelVendorUpdateOne) SaveX(ctx context.Context) *ModelVendor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelVendorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelVendorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelVendorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelvendor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelVendorUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := modelvendor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := modelvendor.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.provider_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconKey(); ok {
		if err := modelvendor.IconKeyValidator(v); err != nil {
			return &ValidationError{Name: "icon_key", err: fmt.Errorf(`ent: validator failed for field "ModelVendor.icon_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelVendorUpdateOne) sqlSave(ctx context.Context) (_node *ModelVendor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelvendor.Table, modelvendor.Columns, sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelVendor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelvendor.FieldID)
		for _, f := range fields {
			if !modelvendor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelvendor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelvendor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(modelvendor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(modelvendor.FieldProviderKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconKey(); ok {
		_spec.SetField(modelvendor.FieldIconKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelvendor.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(modelvendor.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(modelvendor.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(modelvendor.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(modelvendor.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelsIDs(); len(nodes) > 0 && !_u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   modelvendor.ModelsTable,
			Columns: []string{modelvendor.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelVendor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelvendor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
