// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelvendor"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogUpdate is the builder for updating ModelCatalog entities.
type ModelCatalogUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogMutation
}

// Where appends a list predicates to the ModelCatalogUpdate builder.
func (_u *ModelCatalogUpdate) Where(ps ...predicate.ModelCatalog) *ModelCatalogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogUpdate) SetUpdatedAt(v time.Time) *ModelCatalogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelCatalogUpdate) SetModelID(v string) *ModelCatalogUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableModelID(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetNormalizedModelID sets the "normalized_model_id" field.
func (_u *ModelCatalogUpdate) SetNormalizedModelID(v string) *ModelCatalogUpdate {
	_u.mutation.SetNormalizedModelID(v)
	return _u
}

// SetNillableNormalizedModelID sets the "normalized_model_id" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableNormalizedModelID(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetNormalizedModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelCatalogUpdate) SetDisplayName(v string) *ModelCatalogUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableDisplayName(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelCatalogUpdate) SetPlatform(v string) *ModelCatalogUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillablePlatform(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelCatalogUpdate) SetProvider(v string) *ModelCatalogUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableProvider(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetVendorID sets the "vendor_id" field.
func (_u *ModelCatalogUpdate) SetVendorID(v int64) *ModelCatalogUpdate {
	_u.mutation.SetVendorID(v)
	return _u
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableVendorID(v *int64) *ModelCatalogUpdate {
	if v != nil {
		_u.SetVendorID(*v)
	}
	return _u
}

// ClearVendorID clears the value of the "vendor_id" field.
func (_u *ModelCatalogUpdate) ClearVendorID() *ModelCatalogUpdate {
	_u.mutation.ClearVendorID()
	return _u
}

// SetMode sets the "mode" field.
func (_u *ModelCatalogUpdate) SetMode(v string) *ModelCatalogUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableMode(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelCatalogUpdate) SetDescription(v string) *ModelCatalogUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableDescription(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ModelCatalogUpdate) SetTags(v []string) *ModelCatalogUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ModelCatalogUpdate) AppendTags(v []string) *ModelCatalogUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelCatalogUpdate) SetCapabilities(v map[string]interface{}) *ModelCatalogUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetEndpoints sets the "endpoints" field.
func (_u *ModelCatalogUpdate) SetEndpoints(v []string) *ModelCatalogUpdate {
	_u.mutation.SetEndpoints(v)
	return _u
}

// AppendEndpoints appends value to the "endpoints" field.
func (_u *ModelCatalogUpdate) AppendEndpoints(v []string) *ModelCatalogUpdate {
	_u.mutation.AppendEndpoints(v)
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *ModelCatalogUpdate) SetPricing(v map[string]interface{}) *ModelCatalogUpdate {
	_u.mutation.SetPricing(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ModelCatalogUpdate) SetMetadata(v map[string]interface{}) *ModelCatalogUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogUpdate) SetStatus(v modelcatalog.Status) *ModelCatalogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableStatus(v *modelcatalog.Status) *ModelCatalogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ModelCatalogUpdate) SetVisibility(v modelcatalog.Visibility) *ModelCatalogUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableVisibility(v *modelcatalog.Visibility) *ModelCatalogUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ModelCatalogUpdate) SetSource(v string) *ModelCatalogUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableSource(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIconKey sets the "icon_key" field.
func (_u *ModelCatalogUpdate) SetIconKey(v string) *ModelCatalogUpdate {
	_u.mutation.SetIconKey(v)
	return _u
}

// SetNillableIconKey sets the "icon_key" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableIconKey(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetIconKey(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ModelCatalogUpdate) SetLastSyncedAt(v time.Time) *ModelCatalogUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableLastSyncedAt(v *time.Time) *ModelCatalogUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ModelCatalogUpdate) ClearLastSyncedAt() *ModelCatalogUpdate {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetVendor sets the "vendor" edge to the ModelVendor entity.
func (_u *ModelCatalogUpdate) SetVendor(v *ModelVendor) *ModelCatalogUpdate {
	return _u.SetVendorID(v.ID)
}

// Mutation returns the ModelCatalogMutation object of the builder.
func (_u *ModelCatalogUpdate) Mutation() *ModelCatalogMutation {
	return _u.mutation
}

// ClearVendor clears the "vendor" edge to the ModelVendor entity.
func (_u *ModelCatalogUpdate) ClearVendor() *ModelCatalogUpdate {
	_u.mutation.ClearVendor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelcatalog.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedModelID(); ok {
		if err := modelcatalog.NormalizedModelIDValidator(v); err != nil {
			return &ValidationError{Name: "normalized_model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.normalized_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelcatalog.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelcatalog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := modelcatalog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := modelcatalog.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := modelcatalog.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := modelcatalog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconKey(); ok {
		if err := modelcatalog.IconKeyValidator(v); err != nil {
			return &ValidationError{Name: "icon_key", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.icon_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalog.Table, modelcatalog.Columns, sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelcatalog.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedModelID(); ok {
		_spec.SetField(modelcatalog.FieldNormalizedModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelcatalog.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelcatalog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelcatalog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(modelcatalog.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelcatalog.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(modelcatalog.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalog.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(modelcatalog.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Endpoints(); ok {
		_spec.SetField(modelcatalog.FieldEndpoints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpoints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalog.FieldEndpoints, value)
		})
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(modelcatalog.FieldPricing, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(modelcatalog.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(modelcatalog.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(modelcatalog.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconKey(); ok {
		_spec.SetField(modelcatalog.FieldIconKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(modelcatalog.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(modelcatalog.FieldLastSyncedAt, field.TypeTime)
	}
	if _u.mutation.VendorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalog.VendorTable,
			Columns: []string{modelcatalog.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalog.VendorTable,
			Columns: []string{modelcatalog.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogUpdateOne is the builder for updating a single ModelCatalog entity.
type ModelCatalogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelCatalogUpdateOne) SetModelID(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableModelID(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetNormalizedModelID sets the "normalized_model_id" field.
func (_u *ModelCatalogUpdateOne) SetNormalizedModelID(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetNormalizedModelID(v)
	return _u
}

// SetNillableNormalizedModelID sets the "normalized_model_id" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableNormalizedModelID(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetNormalizedModelID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *ModelCatalogUpdateOne) SetDisplayName(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableDisplayName(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelCatalogUpdateOne) SetPlatform(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillablePlatform(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelCatalogUpdateOne) SetProvider(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableProvider(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetVendorID sets the "vendor_id" field.
func (_u *ModelCatalogUpdateOne) SetVendorID(v int64) *ModelCatalogUpdateOne {
	_u.mutation.SetVendorID(v)
	return _u
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableVendorID(v *int64) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetVendorID(*v)
	}
	return _u
}

// ClearVendorID clears the value of the "vendor_id" field.
func (_u *ModelCatalogUpdateOne) ClearVendorID() *ModelCatalogUpdateOne {
	_u.mutation.ClearVendorID()
	return _u
}

// SetMode sets the "mode" field.
func (_u *ModelCatalogUpdateOne) SetMode(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableMode(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelCatalogUpdateOne) SetDescription(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableDescription(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ModelCatalogUpdateOne) SetTags(v []string) *ModelCatalogUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ModelCatalogUpdateOne) AppendTags(v []string) *ModelCatalogUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelCatalogUpdateOne) SetCapabilities(v map[string]interface{}) *ModelCatalogUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// SetEndpoints sets the "endpoints" field.
func (_u *ModelCatalogUpdateOne) SetEndpoints(v []string) *ModelCatalogUpdateOne {
	_u.mutation.SetEndpoints(v)
	return _u
}

// AppendEndpoints appends value to the "endpoints" field.
func (_u *ModelCatalogUpdateOne) AppendEndpoints(v []string) *ModelCatalogUpdateOne {
	_u.mutation.AppendEndpoints(v)
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *ModelCatalogUpdateOne) SetPricing(v map[string]interface{}) *ModelCatalogUpdateOne {
	_u.mutation.SetPricing(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ModelCatalogUpdateOne) SetMetadata(v map[string]interface{}) *ModelCatalogUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogUpdateOne) SetStatus(v modelcatalog.Status) *ModelCatalogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableStatus(v *modelcatalog.Status) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *ModelCatalogUpdateOne) SetVisibility(v modelcatalog.Visibility) *ModelCatalogUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableVisibility(v *modelcatalog.Visibility) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *ModelCatalogUpdateOne) SetSource(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableSource(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetIconKey sets the "icon_key" field.
func (_u *ModelCatalogUpdateOne) SetIconKey(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetIconKey(v)
	return _u
}

// SetNillableIconKey sets the "icon_key" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableIconKey(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetIconKey(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *ModelCatalogUpdateOne) SetLastSyncedAt(v time.Time) *ModelCatalogUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableLastSyncedAt(v *time.Time) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// ClearLastSyncedAt clears the value of the "last_synced_at" field.
func (_u *ModelCatalogUpdateOne) ClearLastSyncedAt() *ModelCatalogUpdateOne {
	_u.mutation.ClearLastSyncedAt()
	return _u
}

// SetVendor sets the "vendor" edge to the ModelVendor entity.
func (_u *ModelCatalogUpdateOne) SetVendor(v *ModelVendor) *ModelCatalogUpdateOne {
	return _u.SetVendorID(v.ID)
}

// Mutation returns the ModelCatalogMutation object of the builder.
func (_u *ModelCatalogUpdateOne) Mutation() *ModelCatalogMutation {
	return _u.mutation
}

// ClearVendor clears the "vendor" edge to the ModelVendor entity.
func (_u *ModelCatalogUpdateOne) ClearVendor() *ModelCatalogUpdateOne {
	_u.mutation.ClearVendor()
	return _u
}

// Where appends a list predicates to the ModelCatalogUpdate builder.
func (_u *ModelCatalogUpdateOne) Where(ps ...predicate.ModelCatalog) *ModelCatalogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogUpdateOne) Select(field string, fields ...string) *ModelCatalogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalog entity.
func (_u *ModelCatalogUpdateOne) Save(ctx context.Context) (*ModelCatalog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogUpdateOne) SaveX(ctx context.Context) *ModelCatalog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelcatalog.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NormalizedModelID(); ok {
		if err := modelcatalog.NormalizedModelIDValidator(v); err != nil {
			return &ValidationError{Name: "normalized_model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.normalized_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := modelcatalog.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.display_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelcatalog.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := modelcatalog.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mode(); ok {
		if err := modelcatalog.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Visibility(); ok {
		if err := modelcatalog.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.visibility": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := modelcatalog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconKey(); ok {
		if err := modelcatalog.IconKeyValidator(v); err != nil {
			return &ValidationError{Name: "icon_key", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.icon_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalog.Table, modelcatalog.Columns, sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCatalog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcatalog.FieldID)
		for _, f := range fields {
			if !modelcatalog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcatalog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelcatalog.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NormalizedModelID(); ok {
		_spec.SetField(modelcatalog.FieldNormalizedModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(modelcatalog.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelcatalog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelcatalog.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(modelcatalog.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelcatalog.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(modelcatalog.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalog.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(modelcatalog.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Endpoints(); ok {
		_spec.SetField(modelcatalog.FieldEndpoints, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEndpoints(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalog.FieldEndpoints, value)
		})
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(modelcatalog.FieldPricing, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(modelcatalog.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(modelcatalog.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(modelcatalog.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconKey(); ok {
		_spec.SetField(modelcatalog.FieldIconKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(modelcatalog.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncedAtCleared() {
		_spec.ClearField(modelcatalog.FieldLastSyncedAt, field.TypeTime)
	}
	if _u.mutation.VendorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalog.VendorTable,
			Columns: []string{modelcatalog.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   modelcatalog.VendorTable,
			Columns: []string{modelcatalog.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelvendor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelCatalog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
