// Code generated by ent, DO NOT EDIT.

package modelcatalog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldUpdatedAt, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldModelID, v))
}

// NormalizedModelID applies equality check predicate on the "normalized_model_id" field. It's identical to NormalizedModelIDEQ.
func NormalizedModelID(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldNormalizedModelID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldDisplayName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldPlatform, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldProvider, v))
}

// VendorID applies equality check predicate on the "vendor_id" field. It's identical to VendorIDEQ.
func VendorID(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldVendorID, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldMode, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldDescription, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldSource, v))
}

// IconKey applies equality check predicate on the "icon_key" field. It's identical to IconKeyEQ.
func IconKey(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldIconKey, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldUpdatedAt, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldModelID, v))
}

// NormalizedModelIDEQ applies the EQ predicate on the "normalized_model_id" field.
func NormalizedModelIDEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldNormalizedModelID, v))
}

// NormalizedModelIDNEQ applies the NEQ predicate on the "normalized_model_id" field.
func NormalizedModelIDNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldNormalizedModelID, v))
}

// NormalizedModelIDIn applies the In predicate on the "normalized_model_id" field.
func NormalizedModelIDIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldNormalizedModelID, vs...))
}

// NormalizedModelIDNotIn applies the NotIn predicate on the "normalized_model_id" field.
func NormalizedModelIDNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldNormalizedModelID, vs...))
}

// NormalizedModelIDGT applies the GT predicate on the "normalized_model_id" field.
func NormalizedModelIDGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldNormalizedModelID, v))
}

// NormalizedModelIDGTE applies the GTE predicate on the "normalized_model_id" field.
func NormalizedModelIDGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldNormalizedModelID, v))
}

// NormalizedModelIDLT applies the LT predicate on the "normalized_model_id" field.
func NormalizedModelIDLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldNormalizedModelID, v))
}

// NormalizedModelIDLTE applies the LTE predicate on the "normalized_model_id" field.
func NormalizedModelIDLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldNormalizedModelID, v))
}

// NormalizedModelIDContains applies the Contains predicate on the "normalized_model_id" field.
func NormalizedModelIDContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldNormalizedModelID, v))
}

// NormalizedModelIDHasPrefix applies the HasPrefix predicate on the "normalized_model_id" field.
func NormalizedModelIDHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldNormalizedModelID, v))
}

// NormalizedModelIDHasSuffix applies the HasSuffix predicate on the "normalized_model_id" field.
func NormalizedModelIDHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldNormalizedModelID, v))
}

// NormalizedModelIDEqualFold applies the EqualFold predicate on the "normalized_model_id" field.
func NormalizedModelIDEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldNormalizedModelID, v))
}

// NormalizedModelIDContainsFold applies the ContainsFold predicate on the "normalized_model_id" field.
func NormalizedModelIDContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldNormalizedModelID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldDisplayName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldPlatform, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldProvider, v))
}

// VendorIDEQ applies the EQ predicate on the "vendor_id" field.
func VendorIDEQ(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldVendorID, v))
}

// VendorIDNEQ applies the NEQ predicate on the "vendor_id" field.
func VendorIDNEQ(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldVendorID, v))
}

// VendorIDIn applies the In predicate on the "vendor_id" field.
func VendorIDIn(vs ...int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldVendorID, vs...))
}

// VendorIDNotIn applies the NotIn predicate on the "vendor_id" field.
func VendorIDNotIn(vs ...int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldVendorID, vs...))
}

// VendorIDIsNil applies the IsNil predicate on the "vendor_id" field.
func VendorIDIsNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIsNull(FieldVendorID))
}

// VendorIDNotNil applies the NotNil predicate on the "vendor_id" field.
func VendorIDNotNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotNull(FieldVendorID))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldMode, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldStatus, vs...))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v Visibility) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v Visibility) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...Visibility) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...Visibility) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldVisibility, vs...))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldSource, v))
}

// IconKeyEQ applies the EQ predicate on the "icon_key" field.
func IconKeyEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldIconKey, v))
}

// IconKeyNEQ applies the NEQ predicate on the "icon_key" field.
func IconKeyNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldIconKey, v))
}

// IconKeyIn applies the In predicate on the "icon_key" field.
func IconKeyIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldIconKey, vs...))
}

// IconKeyNotIn applies the NotIn predicate on the "icon_key" field.
func IconKeyNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldIconKey, vs...))
}

// IconKeyGT applies the GT predicate on the "icon_key" field.
func IconKeyGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldIconKey, v))
}

// IconKeyGTE applies the GTE predicate on the "icon_key" field.
func IconKeyGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldIconKey, v))
}

// IconKeyLT applies the LT predicate on the "icon_key" field.
func IconKeyLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldIconKey, v))
}

// IconKeyLTE applies the LTE predicate on the "icon_key" field.
func IconKeyLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldIconKey, v))
}

// IconKeyContains applies the Contains predicate on the "icon_key" field.
func IconKeyContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldIconKey, v))
}

// IconKeyHasPrefix applies the HasPrefix predicate on the "icon_key" field.
func IconKeyHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldIconKey, v))
}

// IconKeyHasSuffix applies the HasSuffix predicate on the "icon_key" field.
func IconKeyHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldIconKey, v))
}

// IconKeyEqualFold applies the EqualFold predicate on the "icon_key" field.
func IconKeyEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldIconKey, v))
}

// IconKeyContainsFold applies the ContainsFold predicate on the "icon_key" field.
func IconKeyContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldIconKey, v))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotNull(FieldLastSyncedAt))
}

// HasVendor applies the HasEdge predicate on the "vendor" edge.
func HasVendor() predicate.ModelCatalog {
	return predicate.ModelCatalog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, VendorTable, VendorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVendorWith applies the HasEdge predicate on the "vendor" edge with a given conditions (other predicates).
func HasVendorWith(preds ...predicate.ModelVendor) predicate.ModelCatalog {
	return predicate.ModelCatalog(func(s *sql.Selector) {
		step := newVendorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelCatalog) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelCatalog) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelCatalog) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.NotPredicates(p))
}
